# hermes_agent/prompt_library/render.py
"""Render Hermes prompt-profile manifests to staging artifacts."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Optional, TypedDict

from hermes_agent.prompt_library.canopy import cn_render, cn_show, cn_version
from hermes_agent.prompt_library.errors import CanopyCliError, CrossTenantInheritError, ManifestValidationError
from hermes_agent.prompt_library.manifest import load_manifest, validate_manifest
from hermes_agent.prompt_library.paths import canopy_project_dir, resolve_library_root
from hermes_agent.prompt_library.profile_check import check_profile_exists
from hermes_agent.prompt_library.warnings import FOSSILIZATION_WARNING


class RenderResult(TypedDict):
    profile: str
    tenant: str
    manifest_path: str
    canopy_cli_version: str
    resolved_from: list
    sections: list
    params_sha256: str
    targets: dict
    fossilization_warning: str
    dry_run: bool
    receipt_path: str


GENERATED_HEADER_TEMPLATE = """<!-- GENERATED BY hermes.prompt_profile.v1
source_manifest: {manifest_path}
profile: {profile}
tenant: {tenant}
sections: {sections}
receipt: {receipt_path}
Do not edit generated region; edit the source manifest/section instead.
-->

"""


def _apply_params(text: str, params: dict) -> str:
    """Apply {{ key }} -> value substitution to text."""
    for k, v in params.items():
        text = text.replace("{{" + k + "}}", str(v))
        text = text.replace("{{ " + k + " }}", str(v))
    return text


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _extract_tenant_tag(tags: list[str]) -> Optional[str]:
    for tag in tags:
        m = re.match(r"^tenant:(.+)$", tag)
        if m:
            return m.group(1)
    return None


def _params_from_manifest(manifest: dict) -> dict:
    """Return v1 render.params, with top-level params as a transition shim."""
    params: dict = {}
    render = manifest.get("render") or {}
    if isinstance(render, dict) and isinstance(render.get("params"), dict):
        params.update(render.get("params") or {})
    if isinstance(manifest.get("params"), dict):
        params.update(manifest.get("params") or {})
    return params


def _assert_safe_rendered_output(targets_out: dict) -> None:
    """Reject obvious secrets and unresolved placeholders in rendered text."""
    secret_markers = ("API_KEY", "TOKEN", ".env", "BEGIN PRIVATE KEY")
    placeholder_patterns = (r"{{\s*[^}]+\s*}}", r"<<[^>]+>>")
    errors: list[dict] = []
    for target_name, target in targets_out.items():
        content = str(target.get("content", ""))
        for marker in secret_markers:
            if marker in content:
                errors.append(
                    {
                        "rule": "V15",
                        "field": f"targets.{target_name}.content",
                        "message": f"Rendered output contains forbidden secret marker: {marker}",
                    }
                )
        for pattern in placeholder_patterns:
            if re.search(pattern, content):
                errors.append(
                    {
                        "rule": "V16",
                        "field": f"targets.{target_name}.content",
                        "message": f"Rendered output contains unresolved placeholder matching {pattern}",
                    }
                )
    if errors:
        raise ManifestValidationError(errors)


def _add_generated_headers(
    targets_out: dict,
    *,
    manifest_path: Path,
    profile: str,
    tenant: str,
    sections: list[dict],
    receipt_path: str,
) -> None:
    section_names = ", ".join(str(s.get("name", "")) for s in sections)
    header = GENERATED_HEADER_TEMPLATE.format(
        manifest_path=str(manifest_path),
        profile=profile,
        tenant=tenant,
        sections=section_names,
        receipt_path=receipt_path,
    )
    for target in targets_out.values():
        target["content"] = header + str(target.get("content", ""))


def render_profile(
    profile: str,
    *,
    library_root: Optional[Path] = None,
    staging_dir: Optional[Path] | bool = None,
) -> RenderResult:
    """Resolve and render a profile without touching live target files.

    Dry-run rendering writes staging artifacts and a receipt by default. Pass
    ``staging_dir=False`` to suppress staging writes while still returning the
    rendered content and receipt.
    """
    from hermes_agent.prompt_library.paths import manifest_path as get_manifest_path
    from hermes_agent.prompt_library.paths import staging_dir as default_staging
    from hermes_agent.prompt_library.receipt import write_receipt

    root = resolve_library_root(library_root)
    proj_dir = canopy_project_dir(root)
    manifest = load_manifest(profile, root)
    validate_manifest(manifest)

    if profile != "gelby-default" and not check_profile_exists(profile):
        raise ManifestValidationError(
            [
                {
                    "rule": "V13",
                    "field": "profile",
                    "message": f"Profile '{profile}' is not in hermes profile list",
                }
            ]
        )

    render_cfg = manifest.get("render") or {}
    render_prompt = render_cfg["prompt"]
    cn_ver = cn_version()
    envelope = cn_render(render_prompt, project_dir=proj_dir, format="json")
    raw_sections = envelope.get("sections", [])
    resolved_from: list[str] = envelope.get("resolvedFrom", [render_prompt])

    profile_tenant = manifest.get("tenant", "")
    allow_list = manifest.get("cross_tenant_inherit_allow", []) or []
    allow_set = {
        (entry.get("prompt"), entry.get("from_tenant"))
        for entry in allow_list
        if isinstance(entry, dict)
    }

    for ancestor_name in resolved_from:
        if ancestor_name == render_prompt:
            continue
        try:
            ancestor_data = cn_show(ancestor_name, project_dir=proj_dir)
            ancestor_tags = ancestor_data.get("tags", []) or (ancestor_data.get("frontmatter") or {}).get("tags", []) or []
            ancestor_tenant = _extract_tenant_tag(ancestor_tags)
            if not ancestor_tenant:
                raise CanopyCliError(
                    f"Cannot verify tenant tag for inherited Canopy prompt '{ancestor_name}'"
                )
            if ancestor_tenant and ancestor_tenant != profile_tenant and (ancestor_name, ancestor_tenant) not in allow_set:
                raise CrossTenantInheritError(
                    prompt=ancestor_name,
                    from_tenant=ancestor_tenant,
                    profile_tenant=profile_tenant,
                )
        except CrossTenantInheritError:
            raise
        except CanopyCliError:
            raise
        except Exception as exc:
            raise CanopyCliError(
                f"Cannot inspect inherited Canopy prompt '{ancestor_name}' with cn show"
            ) from exc

    params = _params_from_manifest(manifest)
    substituted_sections = []
    for sec in raw_sections:
        body = _apply_params(sec.get("body", ""), params)
        substituted_sections.append({"name": sec.get("name", ""), "body": body})

    sections_summary = [
        {"name": s["name"], "sha256": _sha256_text(s["body"])[:7], "body_chars": len(s["body"])}
        for s in substituted_sections
    ]
    params_sha256 = _sha256_text(json.dumps(params, sort_keys=True))

    route_map: dict[str, str] = {}
    for route in manifest.get("section_routes") or []:
        if isinstance(route, dict):
            route_map[route.get("section", "")] = route.get("target", "")

    targets_config = manifest.get("targets", {})
    soul_target = targets_config.get("soul")
    cfg_target = targets_config.get("config_addendum")
    soul_sections: list[dict] = []
    cfg_sections: list[dict] = []

    for sec in substituted_sections:
        target_key = route_map.get(sec["name"])
        if target_key == "soul":
            soul_sections.append(sec)
        elif target_key == "config_addendum":
            cfg_sections.append(sec)
        elif soul_target:
            soul_sections.append(sec)
        elif cfg_target:
            cfg_sections.append(sec)

    targets_out: dict = {}
    if isinstance(soul_target, dict):
        targets_out["soul"] = {
            "path": str(Path(str(soul_target.get("path", ""))).expanduser()),
            "content": "\n\n".join(s["body"] for s in soul_sections),
        }
    if isinstance(cfg_target, dict):
        targets_out["config_addendum"] = {
            "path": str(Path(str(cfg_target.get("path", ""))).expanduser()),
            "key": cfg_target.get("key", ""),
            "content": "\n\n".join(s["body"] for s in cfg_sections),
        }

    _assert_safe_rendered_output(targets_out)

    m_path = get_manifest_path(root, profile)
    receipt_placeholder = str(root / "receipts" / profile / "<pending>.json")
    _add_generated_headers(
        targets_out,
        manifest_path=m_path,
        profile=profile,
        tenant=manifest.get("tenant", ""),
        sections=sections_summary,
        receipt_path=receipt_placeholder,
    )

    effective_staging_dir = default_staging(root, profile) if staging_dir is None else staging_dir
    if effective_staging_dir is not False:
        staging_out = Path(effective_staging_dir)
        # ``staging_dir`` is treated as a staging root unless the caller already
        # passed a profile-specific leaf directory. This preserves the original
        # adapter/test contract (root/<profile>/...) while keeping the CLI's
        # default ``staging/<profile>`` path stable.
        if staging_out.name != profile:
            staging_out = staging_out / profile
        staging_out.mkdir(parents=True, exist_ok=True)
        if "soul" in targets_out:
            (staging_out / "SOUL.md.rendered").write_text(targets_out["soul"]["content"], encoding="utf-8")
        if "config_addendum" in targets_out:
            (staging_out / "config_addendum.txt").write_text(targets_out["config_addendum"]["content"], encoding="utf-8")

    result = RenderResult(
        profile=profile,
        tenant=manifest.get("tenant", ""),
        manifest_path=str(m_path),
        canopy_cli_version=cn_ver,
        resolved_from=resolved_from,
        sections=sections_summary,
        params_sha256=params_sha256,
        targets=targets_out,
        fossilization_warning=FOSSILIZATION_WARNING,
        dry_run=True,
        receipt_path="",
    )
    receipt_path = write_receipt(profile, result, dry_run=True, library_root=root)
    result["receipt_path"] = str(receipt_path)
    return result
