from __future__ import annotations

import builtins
import json
import os
from pathlib import Path
import subprocess
import sys

import pytest
import yaml


MOCK_RENDER = {
    "success": True,
    "name": "tac-builder-profile",
    "version": 1,
    "resolvedFrom": ["tac-builder-profile"],
    "frontmatter": {"tags": ["tenant:gbautomation"]},
    "sections": [
        {"name": "identity", "body": "You are {{ profile_display_name }}.\n"},
        {"name": "ops", "body": "Use board {{ board }}.\n"},
    ],
}


def _write_manifest(library_root: Path, hermes_home: Path, *, profile: str = "tac-builder") -> Path:
    profiles_dir = library_root / "profiles"
    profiles_dir.mkdir(parents=True)
    manifest_path = profiles_dir / f"{profile}.yaml"
    manifest = {
        "schema": "hermes.prompt_profile.v1",
        "profile": profile,
        "tenant": "gbautomation",
        "owner": "greg",
        "render": {
            "adapter": "canopy",
            "prompt": "tac-builder-profile",
            "params": {"profile_display_name": "TAC Builder", "board": "gbautomation"},
        },
        "targets": {
            "soul": {
                "path": str(hermes_home / "profiles" / profile / "SOUL.md"),
                "mode": "replace",
            },
            "config_addendum": {
                "path": str(hermes_home / "profiles" / profile / "config.yaml"),
                "key": "system_prompt_addendum",
                "mode": "replace",
            },
        },
        "section_routes": [
            {"section": "identity", "target": "soul"},
            {"section": "ops", "target": "config_addendum"},
        ],
    }
    manifest_path.write_text(yaml.safe_dump(manifest), encoding="utf-8")
    return manifest_path


@pytest.fixture
def mocked_canopy(monkeypatch):
    from hermes_agent.prompt_library import render as render_mod

    monkeypatch.setattr(render_mod, "cn_version", lambda: "0.2.6")
    monkeypatch.setattr(render_mod, "cn_render", lambda *a, **kw: MOCK_RENDER)
    monkeypatch.setattr(
        render_mod,
        "cn_show",
        lambda name, project_dir: {"frontmatter": {"tags": ["tenant:gbautomation"]}},
    )
    monkeypatch.setattr(render_mod, "check_profile_exists", lambda profile: True)


def test_render_dry_run_writes_staging_and_receipt_only(tmp_path, monkeypatch, mocked_canopy):
    from hermes_agent.prompt_library.render import render_profile

    hermes_home = tmp_path / "home"
    library_root = hermes_home / "prompt-library"
    monkeypatch.setenv("HERMES_HOME", str(hermes_home))
    _write_manifest(library_root, hermes_home)

    result = render_profile("tac-builder", library_root=library_root)

    assert result["dry_run"] is True
    assert Path(result["receipt_path"]).is_file()
    assert (library_root / "staging" / "tac-builder" / "SOUL.md.rendered").read_text(encoding="utf-8").startswith("<!-- GENERATED BY hermes.prompt_profile.v1")
    assert (library_root / "staging" / "tac-builder" / "config_addendum.txt").read_text(encoding="utf-8").startswith("<!-- GENERATED BY hermes.prompt_profile.v1")
    assert not (hermes_home / "profiles" / "tac-builder" / "SOUL.md").exists()
    assert not (hermes_home / "profiles" / "tac-builder" / "config.yaml").exists()


def test_apply_requires_fossilization_acknowledgement(tmp_path, monkeypatch, mocked_canopy):
    from hermes_agent.prompt_library.apply import apply_render
    from hermes_agent.prompt_library.errors import FossilizationAcknowledgmentRequiredError

    hermes_home = tmp_path / "home"
    library_root = hermes_home / "prompt-library"
    monkeypatch.setenv("HERMES_HOME", str(hermes_home))
    _write_manifest(library_root, hermes_home)

    with pytest.raises(FossilizationAcknowledgmentRequiredError):
        apply_render("tac-builder", library_root=library_root, acknowledged_fossilization=False)


def test_apply_patches_config_addendum_and_preserves_unrelated_keys(tmp_path, monkeypatch, mocked_canopy):
    from hermes_agent.prompt_library.apply import apply_render

    hermes_home = tmp_path / "home"
    profile_home = hermes_home / "profiles" / "tac-builder"
    profile_home.mkdir(parents=True)
    (profile_home / "SOUL.md").write_text("old soul\n", encoding="utf-8")
    (profile_home / "config.yaml").write_text(
        "model:\n  provider: openrouter\n  default: old-model\ntools:\n  enabled: true\nsystem_prompt_addendum: old addendum\n",
        encoding="utf-8",
    )
    library_root = hermes_home / "prompt-library"
    monkeypatch.setenv("HERMES_HOME", str(hermes_home))
    _write_manifest(library_root, hermes_home)

    result = apply_render("tac-builder", library_root=library_root, acknowledged_fossilization=True)

    updated = yaml.safe_load((profile_home / "config.yaml").read_text(encoding="utf-8"))
    assert updated["model"] == {"provider": "openrouter", "default": "old-model"}
    assert updated["tools"] == {"enabled": True}
    assert "Use board gbautomation" in updated["system_prompt_addendum"]
    assert Path(result["backup_dir"]).is_dir()
    assert Path(result["receipt_path"]).is_file()


def test_render_does_not_read_secret_files(tmp_path, monkeypatch, mocked_canopy):
    from hermes_agent.prompt_library.render import render_profile

    hermes_home = tmp_path / "home"
    hermes_home.mkdir()
    (hermes_home / ".env").write_text("HERMES_SHOULD_NOT_READ=1\n", encoding="utf-8")
    (hermes_home / "auth.json").write_text(json.dumps({"secret": "do-not-read"}), encoding="utf-8")
    library_root = hermes_home / "prompt-library"
    monkeypatch.setenv("HERMES_HOME", str(hermes_home))
    _write_manifest(library_root, hermes_home)

    original_open = builtins.open
    opened_secret_files: list[str] = []

    def recording_open(file, *args, **kwargs):
        path = str(file)
        if path.endswith("/.env") or path.endswith("/auth.json"):
            opened_secret_files.append(path)
        return original_open(file, *args, **kwargs)

    monkeypatch.setattr(builtins, "open", recording_open)
    render_profile("tac-builder", library_root=library_root)

    assert opened_secret_files == []


def test_prompts_cli_render_is_dry_run_by_default_with_fake_canopy(tmp_path):
    hermes_home = tmp_path / "home"
    library_root = hermes_home / "prompt-library"
    fake_bin = tmp_path / "bin"
    (library_root / "profiles").mkdir(parents=True)
    (library_root / ".canopy").mkdir()
    fake_bin.mkdir()

    manifest = {
        "schema": "hermes.prompt_profile.v1",
        "profile": "gelby-default",
        "tenant": "gbautomation",
        "owner": "greg",
        "render": {"adapter": "canopy", "prompt": "gelby-default", "params": {"name": "Gelby"}},
        "targets": {"soul": {"path": str(tmp_path / "live" / "SOUL.md"), "mode": "replace"}},
        "section_routes": [{"section": "identity", "target": "soul"}],
    }
    (library_root / "profiles" / "gelby-default.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    fake_cn = fake_bin / "cn"
    fake_cn.write_text(
        "#!/usr/bin/env python3\n"
        "import json, sys\n"
        "if '--version' in sys.argv:\n"
        "    print('canopy/0.2.6')\n"
        "elif sys.argv[1] == 'render':\n"
        "    print(json.dumps({'success': True, 'name': sys.argv[2], 'version': 1, 'resolvedFrom': [sys.argv[2]], 'sections': [{'name': 'identity', 'body': 'Hello {{ name }}'}]}))\n"
        "elif sys.argv[1] == 'show':\n"
        "    print(json.dumps({'tags': ['tenant:gbautomation']}))\n",
        encoding="utf-8",
    )
    fake_cn.chmod(0o755)

    env = os.environ.copy()
    env["HERMES_HOME"] = str(hermes_home)
    env["PATH"] = f"{fake_bin}{os.pathsep}{env.get('PATH', '')}"
    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "hermes_cli.main",
            "prompts",
            "render",
            "gelby-default",
            "--library-root",
            str(library_root),
            "--json",
        ],
        cwd=Path(__file__).parents[2],
        env=env,
        text=True,
        capture_output=True,
        timeout=30,
        check=True,
    )
    result = json.loads(completed.stdout)

    assert result["dry_run"] is True
    assert Path(result["receipt_path"]).is_file()
    assert (library_root / "staging" / "gelby-default" / "SOUL.md.rendered").is_file()
    assert not (tmp_path / "live" / "SOUL.md").exists()


def test_prompts_cli_doctor_returns_nonzero_when_canopy_missing(tmp_path):
    env = os.environ.copy()
    env["HERMES_HOME"] = str(tmp_path / "home")
    env["PATH"] = str(tmp_path / "empty-bin")
    (tmp_path / "empty-bin").mkdir()

    completed = subprocess.run(
        [sys.executable, "-m", "hermes_cli.main", "prompts", "doctor"],
        cwd=Path(__file__).parents[2],
        env=env,
        text=True,
        capture_output=True,
        timeout=30,
    )

    assert completed.returncode == 1
    assert "cn not found" in completed.stdout


def test_render_rejects_cross_tenant_inheritance_without_allow_list(tmp_path, monkeypatch):
    from hermes_agent.prompt_library.errors import CrossTenantInheritError
    from hermes_agent.prompt_library.render import render_profile
    from hermes_agent.prompt_library import render as render_mod

    hermes_home = tmp_path / "home"
    library_root = hermes_home / "prompt-library"
    monkeypatch.setenv("HERMES_HOME", str(hermes_home))
    _write_manifest(library_root, hermes_home)
    envelope = dict(MOCK_RENDER)
    envelope["resolvedFrom"] = ["tac-builder-profile", "shared-safety"]

    monkeypatch.setattr(render_mod, "cn_version", lambda: "0.2.6")
    monkeypatch.setattr(render_mod, "cn_render", lambda *a, **kw: envelope)
    monkeypatch.setattr(render_mod, "cn_show", lambda name, project_dir: {"tags": ["tenant:other"]})
    monkeypatch.setattr(render_mod, "check_profile_exists", lambda profile: True)

    with pytest.raises(CrossTenantInheritError):
        render_profile("tac-builder", library_root=library_root)


def test_render_accepts_cross_tenant_inheritance_with_allow_list(tmp_path, monkeypatch):
    from hermes_agent.prompt_library.render import render_profile
    from hermes_agent.prompt_library import render as render_mod

    hermes_home = tmp_path / "home"
    library_root = hermes_home / "prompt-library"
    monkeypatch.setenv("HERMES_HOME", str(hermes_home))
    manifest_path = _write_manifest(library_root, hermes_home)
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    manifest["cross_tenant_inherit_allow"] = [
        {"prompt": "shared-safety", "from_tenant": "other"}
    ]
    manifest_path.write_text(yaml.safe_dump(manifest), encoding="utf-8")
    envelope = dict(MOCK_RENDER)
    envelope["resolvedFrom"] = ["tac-builder-profile", "shared-safety"]

    monkeypatch.setattr(render_mod, "cn_version", lambda: "0.2.6")
    monkeypatch.setattr(render_mod, "cn_render", lambda *a, **kw: envelope)
    monkeypatch.setattr(render_mod, "cn_show", lambda name, project_dir: {"frontmatter": {"tags": ["tenant:other"]}})
    monkeypatch.setattr(render_mod, "check_profile_exists", lambda profile: True)

    result = render_profile("tac-builder", library_root=library_root)

    assert result["resolved_from"] == ["tac-builder-profile", "shared-safety"]


def test_render_fails_closed_when_inherited_prompt_tenant_cannot_be_verified(tmp_path, monkeypatch):
    from hermes_agent.prompt_library.errors import CanopyCliError
    from hermes_agent.prompt_library.render import render_profile
    from hermes_agent.prompt_library import render as render_mod

    hermes_home = tmp_path / "home"
    library_root = hermes_home / "prompt-library"
    monkeypatch.setenv("HERMES_HOME", str(hermes_home))
    _write_manifest(library_root, hermes_home)
    envelope = dict(MOCK_RENDER)
    envelope["resolvedFrom"] = ["tac-builder-profile", "shared-safety"]

    monkeypatch.setattr(render_mod, "cn_version", lambda: "0.2.6")
    monkeypatch.setattr(render_mod, "cn_render", lambda *a, **kw: envelope)
    monkeypatch.setattr(render_mod, "cn_show", lambda name, project_dir: {})
    monkeypatch.setattr(render_mod, "check_profile_exists", lambda profile: True)

    with pytest.raises(CanopyCliError, match="Cannot verify tenant tag"):
        render_profile("tac-builder", library_root=library_root)
