#!/usr/bin/env python3
"""Install + register the nightly GBAutomation artifact-diff cron.

Hermes ``--no-agent`` cron scripts MUST live inside ``HERMES_HOME/scripts/``
(the scheduler rejects any path that resolves outside it). The real logic lives
in the repo at ``scripts/nightly_artifact_diff.py``, so this installer drops a
tiny launcher into the scripts dir that shells out to the repo script and passes
its stdout through verbatim — then registers the nightly cron job.

Safe by default
---------------
  * No flag       -> writes the launcher and PRINTS the exact ``hermes cron``
                     command (does not touch the scheduler).
  * --register    -> also runs ``hermes cron create`` (idempotent: skips if a
                     job with the same name already exists in jobs.json).

Examples::

    python scripts/install_artifact_diff_cron.py
    python scripts/install_artifact_diff_cron.py --register
    python scripts/install_artifact_diff_cron.py --register --schedule "0 3 * * *" --deliver telegram
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
REPO_SCRIPT = SCRIPT_DIR / "nightly_artifact_diff.py"
LAUNCHER_NAME = "gbauto_artifact_diff.py"
JOB_NAME = "GBAuto nightly artifact diff"


def _cron_create_argv(schedule: str, deliver: str) -> tuple[list[str], Optional[Path]]:
    """Return (argv, cwd) for `cron create`. Prefer the `hermes` console script;
    fall back to `python -m hermes_cli.main` (run from the repo) when it's absent."""
    tail = [
        "cron", "create", schedule,
        "--no-agent", "--script", LAUNCHER_NAME,
        "--name", JOB_NAME, "--deliver", deliver,
    ]
    if shutil.which("hermes"):
        return ["hermes", *tail], None
    return [sys.executable, "-m", "hermes_cli.main", *tail], REPO_ROOT


def resolve_hermes_home(override: str | None) -> Path:
    if override:
        return Path(override).expanduser().resolve()
    env = os.environ.get("HERMES_HOME")
    if env:
        return Path(env).expanduser().resolve()
    return (Path.home() / ".hermes").resolve()


def write_launcher(scripts_dir: Path) -> Path:
    scripts_dir.mkdir(parents=True, exist_ok=True)
    launcher = scripts_dir / LAUNCHER_NAME
    launcher.write_text(
        '#!/usr/bin/env python3\n'
        '"""Auto-generated by scripts/install_artifact_diff_cron.py.\n'
        'Runs the repo nightly artifact diff and passes its stdout through verbatim\n'
        'so the Hermes --no-agent cron delivers the digest (empty = silent)."""\n'
        "import subprocess, sys\n\n"
        f"REPO_SCRIPT = {json.dumps(str(REPO_SCRIPT))}\n\n"
        "proc = subprocess.run([sys.executable, REPO_SCRIPT, *sys.argv[1:]],\n"
        "                      capture_output=True, text=True)\n"
        "sys.stderr.write(proc.stderr)\n"
        "sys.stdout.write(proc.stdout)\n"
        "raise SystemExit(proc.returncode)\n",
        encoding="utf-8",
    )
    return launcher


def job_already_registered(hermes_home: Path) -> bool:
    jobs_file = hermes_home / "cron" / "jobs.json"
    if not jobs_file.exists():
        return False
    try:
        data = json.loads(jobs_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    for job in data.get("jobs", []):
        if (job.get("name") or "").strip() == JOB_NAME:
            return True
        if (job.get("script") or "").strip() == LAUNCHER_NAME:
            return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hermes-home", help="Override HERMES_HOME (default: $HERMES_HOME or ~/.hermes)")
    parser.add_argument("--schedule", default="0 2 * * *", help="Cron schedule (default: 0 2 * * *)")
    parser.add_argument("--deliver", default="local", help="Delivery target (local, telegram, origin, …)")
    parser.add_argument("--register", action="store_true", help="Also run `hermes cron create`")
    parser.add_argument("--force", action="store_true", help="Register even if a same-named job exists")
    args = parser.parse_args()

    if not REPO_SCRIPT.exists():
        print(f"install_artifact_diff_cron: missing {REPO_SCRIPT}", file=sys.stderr)
        return 1

    hermes_home = resolve_hermes_home(args.hermes_home)
    scripts_dir = hermes_home / "scripts"
    launcher = write_launcher(scripts_dir)
    print(f"Launcher installed: {launcher}")
    print(f"  -> execs: {REPO_SCRIPT}")

    cron_cmd, cron_cwd = _cron_create_argv(args.schedule, args.deliver)
    printable = "hermes cron create {} --no-agent --script {} --name {} --deliver {}".format(
        shlex.quote(args.schedule), LAUNCHER_NAME, shlex.quote(JOB_NAME), shlex.quote(args.deliver)
    )

    if not args.register:
        print("\nRegister the nightly cron with:\n  " + printable)
        if cron_cwd is not None:
            print("  (no `hermes` on PATH — `--register` will use `python -m hermes_cli.main` from the repo)")
        print("\n(Re-run with --register to create it automatically.)")
        return 0

    if not args.force and job_already_registered(hermes_home):
        print(f"\nA cron named {JOB_NAME!r} already exists — skipping (use --force to add anyway).")
        return 0

    try:
        result = subprocess.run(
            cron_cmd, check=False, text=True, capture_output=True,
            cwd=str(cron_cwd) if cron_cwd else None,
        )
    except FileNotFoundError:
        print("\nHermes CLI not found. Run this instead:\n  " + printable, file=sys.stderr)
        return 1
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    # The CLI can print "Failed to create job: …" and still exit 0, so verify
    # against the store rather than trusting the return code.
    combined = f"{result.stdout}\n{result.stderr}"
    if result.returncode != 0 or "Failed to create job" in combined or not job_already_registered(hermes_home):
        print("\nCron registration FAILED (job not found in jobs.json). Run manually:\n  " + printable, file=sys.stderr)
        return result.returncode or 1
    print("\nNightly artifact-diff cron registered.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
